services:
  db-trackmyfix:
    image: mysql:8.0
    container_name: db-trackmyfix
    restart: always
    env_file:
      - ./backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - trackmyfix_net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 10s
  trackmyfix:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    image: openjdk17
    container_name: trackmyfix
    mem_limit: 512m
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: "jdbc:mysql://db-trackmyfix:3306/track_my_fix_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
    networks:
      - trackmyfix_net
    ports:
      - 9091:9091
    depends_on:
      db-trackmyfix:
        condition: service_healthy
  front-trackmyfix:
    container_name: front
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
    image: front-trackmyfix
    volumes:
      - ./frontend/src:/usr/code/src
      - ./frontend/index.html:/usr/code/index.html
      - ./frontend/eslint.config.js:/usr/code/eslint.config.js
      - ./frontend/tailwind.config.js:/usr/code/tailwind.config.js
      - ./frontend/postcss.config.js:/usr/code/postcss.config.js
      - ./frontend/vite.config.js:/usr/code/vite.config.js
    ports:
      - 5173:5173
    command: npm run host
    environment:
      VITE_BACKEND_URL: http://trackmyfix:9091
