services:
  db-trackmyfix:
    image: mysql:8.0
    container_name: db-trackmyfix
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - trackmyfix_net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 10s
  trackmyfix:
    build:
      dockerfile: Dockerfile
      context: ./
    image: openjdk17
    container_name: trackmyfix
    mem_limit: 512m
    environment:
      DB_HOST: "jdbc:mysql://db-trackmyfix:3306/track_my_fix_db?createDatabaseIfNotExist=true&serverTimezone=UTC"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
    networks:
      - trackmyfix_net
    ports:
      - 9091:9091
    depends_on:
      db-trackmyfix:
        condition: service_healthy
networks:
  trackmyfix_net:
    external: true
