package com.trackmyfix.trackmyfix.entity;

import jakarta.persistence.Entity;

public enum Action {
    CREO_ORDEN_TRABAJO,
    MODIFICO_ORDEN_TRABAJO,
    ELIMINO_ORDEN_TRABAJO,
    ACTIVO_ORDEN_TRABAJO,
    AGREGO_DISPOSITIVO,
    ELIMINO_DISPOSITIVO,
    MODIFICO_DATOS_DISPOSITIVO,
    CAMBIO_ESTADO_DISPOSITIVO,
    CAMBIO_TIPO_DISPOSITIVO,
    CAMBIO_REPORTE_TECNICO_DISPOSITIVO,
    CAMBIO_REPORTE_CLIENTE_DISPOSITIVO,
    CAMBIO_PRECIO_FINAL_DISPOSITIVO,
    CAMBIO_PRECIO_INICIAL_DISPOSITIVO,
    CAMBIO_ACCESORIOS_DISPOSITIVO,
    CAMBIO_MODELO_DISPOSITIVO,
    CAMBIO_NROSERIE_DISPOSITIVO
}
