--DROP DATABASE IF EXISTS `track_my_fix_db`;
--CREATE DATABASE if not exists `track_my_fix_db`;
--
--use `track_my_fix_db`;
--
---- track_my_fix_db.`user` definition
--
--CREATE TABLE `user` (
--  `active` bit(1) NOT NULL,
--  `created_at` datetime(6) NOT NULL DEFAULT(CURRENT_TIMESTAMP),
--  `id_user` bigint NOT NULL AUTO_INCREMENT,
--  `updated_at` datetime(6) DEFAULT NULL,
--  `dni` varchar(20) NOT NULL,
--  `phone` varchar(20) DEFAULT NULL,
--  `discriminator` varchar(31) NOT NULL,
--  `email` varchar(100) NOT NULL,
--  `last_name` varchar(100) NOT NULL,
--  `name` varchar(100) NOT NULL,
--  `password` varchar(100) DEFAULT NULL,
--  `address` varchar(250) NOT NULL,
--  `role` enum('ADMIN','CLIENT','TECHNICIAN') NOT NULL,
--  PRIMARY KEY (`id_user`),
--  UNIQUE KEY `UKjq0ta6mef3p0o47ysw6sflcdl` (`dni`),
--  UNIQUE KEY `UKob8kqyqqgmefl0aco34akdtpe` (`email`)
--) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
---- track_my_fix_db.`order` definition
--
--CREATE TABLE `order` (
--  `active` bit(1) NOT NULL,
--  `order_total` decimal(10,2) NOT NULL,
--  `created_at` datetime(6) NOT NULL DEFAULT(CURRENT_TIMESTAMP),
--  `id_client` bigint NOT NULL,
--  `id_order` bigint NOT NULL AUTO_INCREMENT,
--  `updated_at` datetime(6) DEFAULT NULL,
--  `number` varchar(25) NOT NULL,
--  `observations` text,
--  PRIMARY KEY (`id_order`),
--  UNIQUE KEY `UKb7wobkdwgx8ml5lemn0xr5a0m` (`number`),
--  KEY `FKdl6uu1yeapd67g53j7frsun9j` (`id_client`),
--  CONSTRAINT `FKdl6uu1yeapd67g53j7frsun9j` FOREIGN KEY (`id_client`) REFERENCES `user` (`id_user`)
--) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
---- track_my_fix_db.device definition
--
--CREATE TABLE `device` (
--  `final_price` decimal(10,2) DEFAULT NULL,
--  `initial_price` decimal(10,2) NOT NULL,
--  `created_at` datetime(6) NOT NULL DEFAULT(CURRENT_TIMESTAMP),
--  `id_device` bigint NOT NULL AUTO_INCREMENT,
--  `id_order` bigint NOT NULL,
--  `updated_at` datetime(6) DEFAULT NULL,
--  `model` varchar(100) NOT NULL,
--  `serial_number` varchar(100) NOT NULL,
--  `accessories` varchar(250) DEFAULT NULL,
--  `client_description` text,
--  `technical_report` text,
--  `state` enum('CANCELADO','ENTREGADO','EN_DIAGNOSTICO','EN_PRUEBAS','EN_REPARACION','ESPERANDO_APROBACION','ESPERANDO_REPUESTOS','LISTO_PARA_RETIRO','NO_REPARABLE','RECIBIDO','REPARADO') NOT NULL,
--  `type` enum('COMPUTADORA_DE_ESCRITORIO','COMPUTADORA_PORTATIL','CONSOLA_DE_VIDEOJUEGOS','DISCO_DURO_EXTERNO','ESCANER','FUENTE_DE_PODER','IMPRESORA','LECTOR_DE_CODIGOS_DE_BARRA','MEMORIA_USB','MONITOR','MOUSE','NOTEBOOK','PLACA_BASE','PROYECTOR','ROUTER','SERVIDOR','SMARTPHONE','SWITCH_RED','TABLET','TARJETA_GRAFICA','TECLADO') NOT NULL,
--  PRIMARY KEY (`id_device`),
--  UNIQUE KEY `UK4776vaiywo1kdis4lp8jkm0av` (`serial_number`),
--  KEY `FKe6i24hgvnfhmh3u9qqed7frcx` (`id_order`),
--  CONSTRAINT `FKe6i24hgvnfhmh3u9qqed7frcx` FOREIGN KEY (`id_order`) REFERENCES `order` (`id_order`)
--) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
---- track_my_fix_db.movement definition
--
--CREATE TABLE `movement` (
--  `id_device` bigint NOT NULL,
--  `id_movement` bigint NOT NULL AUTO_INCREMENT,
--  `id_order` bigint NOT NULL,
--  `id_technician` bigint NOT NULL,
--  `movement_date` datetime(6) NOT NULL,
--  `description` text,
--  `action` enum('ACTIVO_ORDEN_TRABAJO','AGREGO_DISPOSITIVO','CAMBIO_ACCESORIOS_DISPOSITIVO','CAMBIO_ESTADO_DISPOSITIVO','CAMBIO_MODELO_DISPOSITIVO','CAMBIO_NROSERIE_DISPOSITIVO','CAMBIO_PRECIO_FINAL_DISPOSITIVO','CAMBIO_PRECIO_INICIAL_DISPOSITIVO','CAMBIO_REPORTE_CLIENTE_DISPOSITIVO','CAMBIO_REPORTE_TECNICO_DISPOSITIVO','CAMBIO_TIPO_DISPOSITIVO','CREO_ORDEN_TRABAJO','ELIMINO_DISPOSITIVO','ELIMINO_ORDEN_TRABAJO','MODIFICO_DATOS_DISPOSITIVO','MODIFICO_ORDEN_TRABAJO') NOT NULL,
--  PRIMARY KEY (`id_movement`),
--  KEY `FKmd2n32u9bgedhiyb2y9bg7ekj` (`id_device`),
--  KEY `FKb2e1s3ohqb4x97tvxnwce77bl` (`id_order`),
--  KEY `FK4ir1hearf352rgk75ojhl4575` (`id_technician`),
--  CONSTRAINT `FK4ir1hearf352rgk75ojhl4575` FOREIGN KEY (`id_technician`) REFERENCES `user` (`id_user`),
--  CONSTRAINT `FKb2e1s3ohqb4x97tvxnwce77bl` FOREIGN KEY (`id_order`) REFERENCES `order` (`id_order`),
--  CONSTRAINT `FKmd2n32u9bgedhiyb2y9bg7ekj` FOREIGN KEY (`id_device`) REFERENCES `device` (`id_device`)
--) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
--
---- track_my_fix_db.user_change definition
--
--CREATE TABLE `user_change` (
--  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  `id_client` bigint DEFAULT NULL,
--  `id_technician` bigint DEFAULT NULL,
--  `id_user_change` bigint NOT NULL AUTO_INCREMENT,
--  `action_user` enum('ACTIVO_CUENTA_CLIENTE','AGREGO_CLIENTE','DESACTIVO_CUENTA_CLIENTE','ELIMINO_CLIENTE','MODIFICO_DATOS_CLIENTE') NOT NULL,
--  PRIMARY KEY (`id_user_change`),
--  KEY `FKk3hvib3wgork3mj7578oruc9p` (`id_client`),
--  KEY `FKojdfroe69ex2yg6jue5jg448f` (`id_technician`),
--  CONSTRAINT `FKk3hvib3wgork3mj7578oruc9p` FOREIGN KEY (`id_client`) REFERENCES `user` (`id_user`),
--  CONSTRAINT `FKojdfroe69ex2yg6jue5jg448f` FOREIGN KEY (`id_technician`) REFERENCES `user` (`id_user`)
--) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
